/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo.crud;

import org.junit.Test;
import static org.junit.Assert.*;

public class WebApplicationTest {
    @Test public void testSomeLibraryMethod() {
        WebApplication classUnderTest = new WebApplication();
        // assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
